# Generated by Django 5.1.3 on 2024-11-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("username",)},
        ),
    ]
